fiends:
  - id: 1
    title: 石木古月的小窝
    url: https://shimuguyue.love
    description: 本站，一个技术宅的个人分享，和我一起交朋友呀~
  - id: 2
    title: 闻道
    url: https://wendao.fit
    description: 海森伯格
  - id: 3
    title: 萌神小天的窝
    url: https://www.msxiaotian.top
    description: 一个独立游戏开发者的学习笔记与创作记录